haxe: 3

default:
  title: dust
  description: a haxe entity-system
  package: alecmce.dust
  version: 0.0.1
  company: alecmce
  main: DustExamples
  output: dust
  bin: bin
  preloader: nil
  src: src
  width: 800
  height: 600
  fps: 60
  background: 000000
  libs: openfl minject
  assets: assets
  orientation: portrait
  resizable: false
  ndll:
  icon: assets/icon.svg
  debug: true

flash:
  swf_version: 11.4

js:
  libs: jeash

cpp:
  libs: hxcpp
  64bit: true

testing:
  bin: 'bin/test/bin'
  report: 'bin/test/report'
  src: test
  browser: firefox
  resources: assets
  templates: nil
  coverage: nil
  coverage_ignored: nil
  disable_inline: true

webos:
  width: 200
  fullscreen: true

ios:
  fullscreen: true

android:
  fullscreen: true