haxe: 3

default:
  title: dust
  version: 0.0.1
  company: alecmce
  package: alecmce.dust
  debug: false
  src: src
  main: Main
  output: dust
  bin: bin
  width: 800
  height: 600
  fps: 60
  background: ffffff
  libs: nme minject
  assets: assets
  orientation: portrait
  resizable: false
  ndll:
  icon: assets/icon.svg

testing:
  test: test
  bin: 'bin/test/bin'
  report: 'bin/test/report'
  src: src
  browser: firefox
  resources: nil
  templates: nil
  coverage: nil
  coverage_ignored: nil

webos:
  width: 200
  fullscreen: true

ios:
  fullscreen: true

android:
  fullscreen: true